#!/bin/sh

# create the pcf files
bdftopcf MonteCarloMedium.bdf > MonteCarloMedium.pcf

# install the fonts
mkfontdir ~/.fonts/MonteCarlo-glyphes
mkfontscale ~/.fonts/MonteCarlo-glyphes
xset +fp ~/.fonts/MonteCarlo-glyphes
xset fp rehash
fc-cache -fv .
