#!/bin/sh
case $1 in
desktop-plus)
	current=$(bspc query -D | wc -l)
	if [ "$current" -lt "10" ]; then
		new=$((current + 1))
		bspc monitor -a $new
	fi
;;
desktop-less)
	current=$(bspc query -D | wc -l)
	if [ "$current" -gt "4" ]; then
        bspc monitor -r $(bspc query -D | sed -n ${current}p)
	fi
;;
*)
	exit
;;
esac
