#! /bin/sh
if [ $(pgrep -cx bspwmpanel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar-aint-recursive}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding 18

bspc control --subscribe > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S  \f3 \f2%d \fr%b  \f3\fr %H:%M ' > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | bspwmpanel-bar | bar-aint-recursive &

wait
