#!/bin/bash

Couleurinfo=[37m
Couleurtext=[36m

## Uptime
			uptime=$(</proc/uptime)
			uptime=${uptime//.*}

	if [[ -n ${uptime} ]]; then
		secs=$((${uptime}%60))
		mins=$((${uptime}/60%60))
		hours=$((${uptime}/3600%24))
		days=$((${uptime}/86400))
		uptime="${mins}"
		if [ "${hours}" -ne "0" ]; then
			uptime="${hours}h ${uptime}m"
		fi
		if [ "${days}" == "1" ]; then
			uptime="${days} day, ${uptime}"
		fi
		if [ "${days}" > "1" ]; then
		   	uptime="${days} days, ${uptime}"
		fi
	fi



## Mémoire
	hw_mem=0
	free_mem=0
	human=1024

	mem_info=$(</proc/meminfo)
		mem_info=$(echo $(echo $(mem_info=${mem_info// /}; echo ${mem_info//kB/})))
		for m in $mem_info; do
			if [[ ${m//:*} = MemTotal ]]; then
				memtotal=${m//*:}
			fi

			if [[ ${m//:*} = MemFree ]]; then
				memfree=${m//*:}
			fi

			if [[ ${m//:*} = Buffers ]]; then
				membuffer=${m//*:}
			fi

			if [[ ${m//:*} = Cached ]]; then
				memcached=${m//*:}
			fi
		done

		usedmem="$(((($memtotal - $memfree) - $membuffer - $memcached) / $human))"
		totalmem="$(($memtotal / $human))"

	mem="${usedmem}MB / ${totalmem}MB"
	[[ "$verbosity" -eq "1" ]] && verboseOut "Finding current RAM usage...found as '$mem'"


cat << EOF

   [30m      ██         ██
   [30m     █[34m██[30m██     ██[34m██[30m█
   [30m    █[34m█████[30m█████[34m█████[30m█
   [30m   █[34m████[30m██[36m█████[30m██[34m████[30m█
   [30m   █[34m███[30m█[36m█████████[30m█[34m███[30m█
   [30m   █[34m██[30m█[36m███████████[30m█[34m██[30m█         ${Couleurtext}User: $Couleurinfo${USER}
   [30m   █[34m██[30m█[36m███████████[30m█[34m██[30m█         ${Couleurtext}Hostname: $Couleurinfo${HOSTNAME}
   [30m   █[34m█[30m█[36m█████████████[30m█[34m█[30m█         ${Couleurtext}Distro: ${Couleurinfo}CirnOS
   [30m   █[34m█[30m█[36m█████████████[30m█[34m█[30m█         ${Couleurtext}Kernel: $Couleurinfo$(uname -srm| sed "s/ARCH/cirno/g")
   [30m    ██[36m██[30m██[36m███[30m█[36m██[30m█[36m██[30m██          ${Couleurtext}Window Manager: [37mbspwm
   [30m  ██[34m█[30m█[36m██[30m█[37m█[30m█[36m█[30m█[37m█[30m█[36m█[30m██[36m█[30m█[34m█[30m██        ${Couleurtext}Desktop Environment: ${Couleurinfo}
   [30m █[34m███[30m█[36m█[30m█[37m███[30m█[37m███[30m█[37m█[30m█[36m█[30m█[34m███[30m█       ${Couleurtext}Shell: $Couleurinfo$(echo $SHELL)
   [30m  █[34m██[30m█[36m█[30m█[37m██[30m█[37m███[30m█[37m██[30m█[36m█[30m█[34m██[30m█        ${Couleurtext}Terminal: ${Couleurinfo}$(echo $TERM)
   [30m   █[34m█[30m█[36m█[30m█[37m██[30m█[37m███[30m█[37m██[30m█[36m█[30m█[34m█[30m█         ${Couleurtext}
   [30m    ██[36m██[30m█[37m█[30m█[37m███[30m█[37m█[30m█[36m██[30m██          ${Couleurtext}Packages: $Couleurinfo$(pacman -Qq | wc -l)
   [30m      █[36m█[30m██[37m█████[30m██[36m█[30m█            ${Couleurtext}Uptime: $Couleurinfo$uptime
   [30m       █  ██[30m█[30m██  █             ${Couleurtext}RAM: $Couleurinfo$mem

EOF
