#!/bin/bash

while inp=$(echo -e "$oup" | dmenu -x 490 -y 330 -w 300 -h 20 -l 4 -fn MonteCarlo-8 -nb '#0d0706' -sb '#740000')
do
    if oup2=$(echo "$inp" | bc -l); then
        echo -n "$oup2" | xsel -i
        oup="$oup2\n$oup"
    fi
done
