#!/bin/bash

while inp=$(echo -e "$oup" | dmenu -x 490 -y 330 -w 300 -h 20 -l 4 -fn 'Lucida Grande-8' -nb '#201f1d' -nf '#eddec9' -sb '#8f3724' -sf '#eddec9')
do
    if oup2=$(echo "$inp" | bc -l); then
        echo -n "$oup2" | xsel -i
        oup="$oup2\n$oup"
    fi
done
