#!/bin/bash

. panel-settings

## Some case test, to see what we are changing
while getopts ":bBvV" flags; do
	case $flags in
	b) # backlight
		title="Sc"
		setting=""
		down="sudo mbp_backlight down ; not-stat -b &"
		up="sudo mbp_backlight up ; not-stat -b &"
	;;
	B) # keyboard backlight
		title="Kb"
		setting=""
		down="sudo keyboard-backlight down ; not-stat -B &"
		up="sudo keyboard-backlight up ; not-stat -B &"
	;;
	v) # PCM volume
		title="Vp"
		setting="%{A:amixer set Master toggle ; not-stat -M &:}M%{A} "
		down="amixer set PCM 1dB- > /dev/null ; not-stat -v &"
		up="amixer set PCM 1dB+ > /dev/null ; not-stat -v &"
	;;
	V) # Master Volume
		title="Vm"
		setting="%{A:amixer set Master toggle ; not-stat -M &:}M%{A} "
		down="amixer set Master 1dB- ; not-stat -V &"
		up="amixer set Master 1dB+ ; not-stat -V &"
	;;
	esac
done
## Fin du test

echo "c" "%{B$bg_button}%{F$fg_button}%{A:panel-monitor:} $title %{A}%{B$bg_monitor}%{F$fg_monitor} $setting%{A:$down:}%{A}%{A:$up:}%{A} %{F$fg_close}%{A:echo c > /tmp/panel-fifo:}%{A} %{F-}%{B-}" > /tmp/panel-fifo
