#! /bin/sh

bspc monitor -d 1 2 3 4

bspc config border_width          3
bspc config window_gap            0
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer  true


# SHADOWS
bspc config apply_floating_atom true
bspc config history_aware_focus true
bspc config ignore_ewmh_focus true


#
## COULEURS ##
#

bspc config focused_border_color "#A73E28"
bspc config normal_border_color "#47362C"
bspc config presel_border_color "#C2AD9D"



#
## RÈGLES ##
#

# Flotter
#bspc rule -a wine floating=true
bspc rule -a nitrogen floating=true

# Centrer les fenêtres flottantes
bspc rule -a \* center=true

#
## PANEL
#

bspwmpanel &
plank &
