#! /bin/sh

bspc monitor -d web dev vid foo
#bspc monitor -d    
#bspc monitor -d    

bspc config border_width          1
bspc config window_gap            8
bspc config split_ratio           0.60
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer  true



## COULEURS ##

bspc config focused_border_color "#DDBEB3"
#bspc config active_border_color "#xxx"
bspc config normal_border_color "#141415"
bspc config presel_border_color "#A1B137"
#bspc config focused_locked_border_color "#xxx"
#bspc config active_locked_border_color "#xxx"
#bspc config normal_locked_border_color "#xxx"
#bspc config focused_sticky_border_color "#xxx"
#bspc config active_sticky_border_color "#xxx"
#bspc config normal_sticky_border_color "#xxx"
#bspc config focused_private_border_color "#xxx"
#bspc config active_private_border_color "#xxx"
#bspc config normal_private_border_color "#xxx"
#bspc config urgent_border_color "#xxx"

#bspc config focused_frame_opacity "#xxx"
#bspc config active_frame_opacity "#xxx"
#bspc config normal_frame_opacity "#xxx"



## RÈGLES ##

#bspc rule -a wine floating=on



bspwmpanel &
