#!/bin/bash
#
# dzen2 pop-up calendar
# (c) 2007, by Robert Manea
#
# Modified by tatou so it can be toggled when clicking on the panel.
#
. panel-settings

calendarpid=$(cat ~/.panel/PID/calendar.pid)
new_calendarpid=""

if [[ -n "$calendarpid" ]]; # If there's already a calendar, it will close it
then
	kill $calendarpid
else # If there's no calendar, it will create one
	TODAY=$(expr `date +'%d'` + 0)
	MONTH=`date +'%m'`
	YEAR=`date +'%Y'`
	LINES=$(cal -m | wc -l)

	(
	date +'%A %d %B'
	cal -m | sed -r -e "1,2 s/.*/^fg(#A73E28)&^fg()/"  -e "s/(^| )($TODAY)($| )/\1^bg(#A73E28)^fg(#eddec9)\2^fg()^bg()\3/") | dzen2 -x 1076 -y 26 -h 20 -l $LINES -sa c -ta c -p -e 'onstart=uncollapse;button1=' -tw 196 -w 196 -fn 'MonteCarlo-8' -fg '#eddec9' -bg '#1A1917' & new_calendarpid=$!
fi

# Save the dzen popup PID so the script can check if it's already opened or not
echo $new_calendarpid > ~/.panel/PID/calendar.pid
